export const browserCoreExamples = [
  "omniagent browser status",
  "omniagent browser start",
  "omniagent browser stop",
  "omniagent browser tabs",
  "omniagent browser open https://example.com",
  "omniagent browser focus abcd1234",
  "omniagent browser close abcd1234",
  "omniagent browser screenshot",
  "omniagent browser screenshot --full-page",
  "omniagent browser screenshot --ref 12",
  "omniagent browser snapshot",
  "omniagent browser snapshot --format aria --limit 200",
  "omniagent browser snapshot --efficient",
  "omniagent browser snapshot --labels",
];

export const browserActionExamples = [
  "omniagent browser navigate https://example.com",
  "omniagent browser resize 1280 720",
  "omniagent browser click 12 --double",
  'omniagent browser type 23 "hello" --submit',
  "omniagent browser press Enter",
  "omniagent browser hover 44",
  "omniagent browser drag 10 11",
  "omniagent browser select 9 OptionA OptionB",
  "omniagent browser upload /tmp/omniagent/uploads/file.pdf",
  'omniagent browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "omniagent browser dialog --accept",
  'omniagent browser wait --text "Done"',
  "omniagent browser evaluate --fn '(el) => el.textContent' --ref 7",
  "omniagent browser console --level error",
  "omniagent browser pdf",
];
