name: OmniAgent
options:
  bundleIdPrefix: ai.omniagent
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  OmniAgentKit:
    path: ../shared/OmniAgentKit
  Swabble:
    path: ../../Swabble

schemes:
  OmniAgent:
    shared: true
    build:
      targets:
        OmniAgent: all
    test:
      targets:
        - OmniAgentTests

targets:
  OmniAgent:
    type: application
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: Sources
    dependencies:
      - target: OmniAgentShareExtension
        embed: true
      - target: OmniAgentWatchApp
      - package: OmniAgentKit
      - package: OmniAgentKit
        product: OmniAgentChatUI
      - package: OmniAgentKit
        product: OmniAgentProtocol
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    preBuildScripts:
      - name: SwiftFormat (lint)
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftformat >/dev/null 2>&1; then
            echo "error: swiftformat not found (brew install swiftformat)" >&2
            exit 1
          fi
          swiftformat --lint --config "$SRCROOT/../../.swiftformat" \
            --filelist "$SRCROOT/SwiftSources.input.xcfilelist"
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftlint >/dev/null 2>&1; then
            echo "error: swiftlint not found (brew install swiftlint)" >&2
            exit 1
          fi
          swiftlint lint --config "$SRCROOT/.swiftlint.yml" --use-script-input-file-lists
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_ENTITLEMENTS: Sources/OmniAgent.entitlements
        CODE_SIGN_STYLE: "$(OMNIAGENT_CODE_SIGN_STYLE)"
        DEVELOPMENT_TEAM: "$(OMNIAGENT_DEVELOPMENT_TEAM)"
        PRODUCT_BUNDLE_IDENTIFIER: "$(OMNIAGENT_APP_BUNDLE_ID)"
        PROVISIONING_PROFILE_SPECIFIER: "$(OMNIAGENT_APP_PROFILE)"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_APPINTENTS_METADATA: NO
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: OmniAgent
        CFBundleIconName: AppIcon
        CFBundleURLTypes:
          - CFBundleURLName: ai.omniagent.ios
            CFBundleURLSchemes:
              - omniagent
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - audio
          - remote-notification
        BGTaskSchedulerPermittedIdentifiers:
          - ai.omniagent.ios.bgrefresh
        NSLocalNetworkUsageDescription: OmniAgent discovers and connects to your OmniAgent gateway on the local network.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        NSBonjourServices:
          - _omniagent-gw._tcp
        NSCameraUsageDescription: OmniAgent can capture photos or short video clips when requested via the gateway.
        NSLocationWhenInUseUsageDescription: OmniAgent uses your location when you allow location sharing.
        NSLocationAlwaysAndWhenInUseUsageDescription: OmniAgent can share your location in the background when you enable Always.
        NSMicrophoneUsageDescription: OmniAgent needs microphone access for voice wake.
        NSSpeechRecognitionUsageDescription: OmniAgent uses on-device speech recognition for voice wake.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  OmniAgentShareExtension:
    type: app-extension
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: ShareExtension
    dependencies:
      - package: OmniAgentKit
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: "$(OMNIAGENT_CODE_SIGN_STYLE)"
        DEVELOPMENT_TEAM: "$(OMNIAGENT_DEVELOPMENT_TEAM)"
        PRODUCT_BUNDLE_IDENTIFIER: "$(OMNIAGENT_SHARE_BUNDLE_ID)"
        PROVISIONING_PROFILE_SPECIFIER: "$(OMNIAGENT_SHARE_PROFILE)"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
    info:
      path: ShareExtension/Info.plist
      properties:
        CFBundleDisplayName: OmniAgent Share
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).ShareViewController"
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsImageWithMaxCount: 10
              NSExtensionActivationSupportsMovieWithMaxCount: 1

  OmniAgentWatchApp:
    type: application.watchapp2
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: WatchApp
    dependencies:
      - target: OmniAgentWatchExtension
    configFiles:
      Debug: Config/Signing.xcconfig
      Release: Config/Signing.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "$(OMNIAGENT_WATCH_APP_BUNDLE_ID)"
    info:
      path: WatchApp/Info.plist
      properties:
        CFBundleDisplayName: OmniAgent
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        WKCompanionAppBundleIdentifier: "$(OMNIAGENT_APP_BUNDLE_ID)"
        WKWatchKitApp: true

  OmniAgentWatchExtension:
    type: watchkit2-extension
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: WatchExtension/Sources
    dependencies:
      - sdk: WatchConnectivity.framework
      - sdk: UserNotifications.framework
    configFiles:
      Debug: Config/Signing.xcconfig
      Release: Config/Signing.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "$(OMNIAGENT_WATCH_EXTENSION_BUNDLE_ID)"
    info:
      path: WatchExtension/Info.plist
      properties:
        CFBundleDisplayName: OmniAgent
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        NSExtension:
          NSExtensionAttributes:
            WKAppBundleIdentifier: "$(OMNIAGENT_WATCH_APP_BUNDLE_ID)"
          NSExtensionPointIdentifier: com.apple.watchkit

  OmniAgentTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: OmniAgent
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.omniagent.ios.tests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/OmniAgent.app/OmniAgent"
        BUNDLE_LOADER: "$(TEST_HOST)"
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDisplayName: OmniAgentTests
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
